# Generated by Django 4.0.4 on 2022-05-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_carousel_comment_alter_carousel_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='carousel',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Faol'), (0, 'Nofaol')], default=0),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_uz', models.CharField(max_length=100, verbose_name='Sarlavha (uz)')),
                ('subject_en', models.CharField(max_length=100, verbose_name='Sarlavha (en)')),
                ('content_uz', models.TextField(verbose_name='Izoh (uz)')),
                ('content_en', models.TextField(verbose_name='Izoh (en)')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=main.models.post_upload_to, verbose_name='Rasm')),
                ('read', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.category')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
