# Generated by Django 4.0.4 on 2022-05-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_carousel_status_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='status',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
