# Generated by Django 4.0.4 on 2022-05-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_category_remove_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='image',
        ),
    ]
