# Generated by Django 4.0.4 on 2022-05-31 07:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_carousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='image',
            field=models.ImageField(default=None, upload_to=main.models.carousel_upload_to),
            preserve_default=False,
        ),
    ]
